#!/bin/bash
#
# Copyright (C) 2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_AS="syncthing"
RUN_GRP="users"
SYNCTHING_CONFIG_DIR="/home/${RUN_AS}/.config"
SYNCTHING_CONFIG="${SYNCTHING_CONFIG_DIR}/syncthing/config.xml";
SERVICE="syncthing"
XPATH="//services/${SERVICE}"
XPATH_ENABLE="${XPATH}/enable"

# generate initial config, certs and then exit
export HOME="/home/${RUN_AS}/.config"
/usr/bin/syncthing -generate=/home/${RUN_AS}/.config/syncthing/

address=$(omv_config_get "${XPATH}/address")
port=$(omv_config_get "${XPATH}/port")
maxsend=$(omv_config_get "${XPATH}/maxsend")
maxrecv=$(omv_config_get "${XPATH}/maxrecv")

# Change settings
new="${address}:${port}"
xmlstarlet ed -L -u "/configuration/gui/address" -v ${new} -n ${SYNCTHING_CONFIG}
xmlstarlet ed -L -u "/configuration/options/maxSendKbps" -v ${maxsend} -n ${SYNCTHING_CONFIG}
xmlstarlet ed -L -u "/configuration/options/maxRecvKbps" -v ${maxrecv} -n ${SYNCTHING_CONFIG}

# fix ownership and permissions
chown -R ${RUN_AS}:${RUN_GRP} ${SYNCTHING_CONFIG_DIR}
chmod 0600 ${SYNCTHING_CONFIG}

if [ "$(omv_config_get "${XPATH_ENABLE}")" != "0" ]; then
    invoke-rc.d ${SERVICE} restart
fi

exit 0
