#!/bin/bash
#
# Copyright (C) 2015-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_GRP="users"

SERVICE="syncthing"
XPATH="/config/services/${SERVICE}"
XPATH_USER="${XPATH}/users/user"

SYNCTHING_CONFIG_DIR=".config"
SYNCTHING_CONFIG="${SYNCTHING_CONFIG_DIR}/${SERVICE}/config.xml";

username=$1

if [ "${username}" != "" ]; then
    position="[username='${username}']"
    enable=$(omv_config_get "${XPATH_USER}${position}/enable")

    if [ "${enable}" != "0" ]; then
        home=$(getent passwd ${username} | awk -F: '{print $6}')

        if [ "${home}" != "" ]; then
            port=$(omv_config_get "${XPATH_USER}${position}/port")
            address=$(omv_config_get "${XPATH_USER}${position}/address")
            lport=$(omv_config_get "${XPATH_USER}${position}/lport")
            laddress=$(omv_config_get "${XPATH_USER}${position}/laddress")
            maxsend=$(omv_config_get "${XPATH_USER}${position}/maxsend")
            maxrecv=$(omv_config_get "${XPATH_USER}${position}/maxrecv")

            # create home directory if it does not exist and fix permissions
            mkdir -p ${home}
            chown ${username}:${RUN_GRP} ${home}

            # generate initial config, certs and then exit
            unset HOME
            export HOME="${home}/${SYNCTHING_CONFIG_DIR}"
            /usr/bin/syncthing -generate="${home}/${SYNCTHING_CONFIG_DIR}/syncthing"

            # Change settings
            new="${address}:${port}"
            xmlstarlet ed -L -u "/configuration/gui/address" -v ${new} "${home}/${SYNCTHING_CONFIG}"

            new="tcp://${laddress}:${lport}"
            xmlstarlet ed -L -u "/configuration/options/listenAddress" -v ${new} "${home}/${SYNCTHING_CONFIG}"

            xmlstarlet ed -L -u "/configuration/options/maxSendKbps" -v ${maxsend} "${home}/${SYNCTHING_CONFIG}"
            xmlstarlet ed -L -u "/configuration/options/maxRecvKbps" -v ${maxrecv} "${home}/${SYNCTHING_CONFIG}"

            # fix ownership and permissions
            chown -R ${username}:${RUN_GRP} "${home}/${SYNCTHING_CONFIG_DIR}"
            chmod 0600 "${home}/${SYNCTHING_CONFIG}"
        fi

        systemctl enable ${SERVICE}@${username}.service >/dev/null || true
        systemctl restart ${SERVICE}@${username}.service >/dev/null || true
    else
        systemctl stop ${SERVICE}@${username}.service >/dev/null || true
        systemctl disable ${SERVICE}@${username}.service >/dev/null || true
    fi
fi

exit 0
