#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        omv_config_delete "/config/services/syncthing"
    ;;

    remove)
        if [ -f "/etc/sysctl.d/90openmediavault-syncthing" ]; then
            rm -f /etc/sysctl.d/90openmediavault-syncthing
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
