#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in

    configure)

        SERVICE_GROUP="users"
        SERVICE_XPATH_NAME="syncthing"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            invoke-rc.d --force discosrv stop
            update-rc.d discosrv disable >/dev/null
        fi

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/settings"; then
            omv_config_add_element "${SERVICE_XPATH}" "settings" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/users"; then
            omv_config_add_element "${SERVICE_XPATH}" "users" ""
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
